version: '3'

services:
  mongodb:
    container_name: oscbdb
    image: mongo:4.2.1
    restart: always
    command: mongod --port 65528
    ports:
      - 65528:65528
    volumes:
      - /ps/code/db:/data/db
    networks:
      - oscb-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: oscbdb
      ME_CONFIG_MONGODB_PORT: "65528"
    ports:
      - "0.0.0.0:8081:8081"
    depends_on:
      - mongodb
    networks:
      - oscb-network

  redis:
    image: "redis:6-alpine"
    hostname: redis
    command: redis-server --port 6381 --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      # - 6379:6379
      - 6381:6381
    networks:
      - oscb-network

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq 
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ./rabbitmq.env
    volumes:
      - /ps/code/db/rabbitmq/data/:/var/lib/rabbitmq/
      - /ps/code/db/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - oscb-network

  # nginx-gateway:
  #   image: nginx:stable-alpine
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #     # - /etc/ssl:/etc/ssl
  #   ports:
  #     - 80:80
  #     # - 443:443
  #   restart: always
  #   networks:
  #     - oscb-network

  # web:
  #   build: 
  #     context: ./web/
  #     dockerfile: Dockerfile
  #   container_name: oscbweb
  #   restart: always
  #   ports:
  #     - 8083:8083
  #   volumes:
  #     - Predictions:/app/data/results
  #     - Uploads:/app/data/upload
  #     - Errors:/app/data/errors
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - oscb-network

  celery-api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: oscb_celery_api
    command: python3 main.py
    restart: always
    ports:
      - 5000:5000
    volumes:
      - Predictions:/data/results
      - Uploads:/data/upload
      - Errors:/data/errors
      - user_storage:/usr/src/app/storage/
    networks:
      - oscb-network
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
      - rabbitmq

  worker1:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: oscb_worker1
    command: celery -A main.celery worker --loglevel=info -Q tools,workflows
    # command: celery -A main.celery worker --loglevel=info -Q tools, workflows -P gevent -c 1
    # command: celery --app project.server.tasks.celery worker -P solo
    # command: celery --app project.server.tasks.celery worker -P gevent -c 1
    # command: celery --app project.server.tasks.celery worker --loglevel=info --logfile=project/logs/celery.log -P gevent
    # command: celery multi start 3 -A project.server.tasks.celery worker -l info
    env_file:
      - .env
    deploy:
      resources:
         limits:
            cpus: "10"
    volumes:
      - Predictions:/data/results
      - Uploads:/data/upload
      - Errors:/data/error
      - user_storage:/usr/src/app/storage/

    networks:
      - oscb-network
    depends_on:
      - mongodb
      - redis
      - rabbitmq
      - celery-api

  worker2:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: oscb_worker2
    command: celery -A main.celery worker --loglevel=info -Q tools,workflows
    # command: celery -A main.celery worker --loglevel=info -Q tools, workflows -P gevent -c 1
    # command: celery --app project.server.tasks.celery worker -P solo 
    # command: celery --app project.server.tasks.celery worker -P gevent -c 1
    # command: celery --app project.server.tasks.celery worker --loglevel=info --logfile=project/logs/celery.log -P gevent
    # command: celery multi start 3 -A project.server.tasks.celery worker -l info
    env_file:
      - .env
    deploy:
      resources:
         limits:
            cpus: "10"
    volumes:
      - Predictions:/data/results
      - Uploads:/data/upload
      - Errors:/data/errors
      - user_storage:/usr/src/app/storage/
    networks:
      - oscb-network
    depends_on:
      - mongodb
      - redis
      - rabbitmq
      - celery-api

  worker3:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: oscb_worker3
    command: celery -A main.celery worker --loglevel=info -Q tools,workflows
    # command: celery -A main.celery worker --loglevel=info -Q tools, workflows -P gevent -c 1
    # command: celery --app project.server.tasks.celery worker -P solo 
    # command: celery --app project.server.tasks.celery worker -P gevent -c 1
    # command: celery --app project.server.tasks.celery worker --loglevel=info --logfile=project/logs/celery.log -P gevent
    # command: celery multi start 3 -A project.server.tasks.celery worker -l info
    env_file:
      - .env
    deploy:
      resources:
         limits:
            cpus: "10"
    volumes:
      - Predictions:/data/results
      - Uploads:/data/upload
      - Errors:/data/errors
      - user_storage:/usr/src/app/storage/
    networks:
      - oscb-network
    depends_on:
      - mongodb
      - redis
      - rabbitmq
      - celery-api

  dashboard:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: oscb_dashboard
    command: celery --app main.celery flower --port=5555 --broker=amqp://admin:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@rabbitmq:5672//
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - celery-api
      - rabbitmq
      - redis
    networks:
      - oscb-network
  
  oscb_mysql:
    container_name: oscb_mysql_container
    image: oscb_mysql
    build:
      context: ./ai-single-cell-ui/ai-single-cell-mysql
    volumes:
        - ./mysql_db:/var/lib/mysql
    command:
        [
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
            "--default-authentication-plugin=mysql_native_password",
        ]
    env_file:
        - ./ai-single-cell-ui/.env  
    networks:
      - oscb-network

  oscb_node:
    container_name: oscb_node_container
    image: oscb_node
    build:
      context: ./ai-single-cell-ui/ai-single-cell-node
    ports:
      - "3001:3001"
      - "3020:3020"
    environment:
      - EXTERNAL_PORT=3001
      - DBUSER=root
      - DBPASSWORD=Shirley@2410
      - DATABASE=aisinglecell
      - HOST=oscb_mysql # NAME OF THE SERVICE
      - HOST_URL=${HOST}
      - SSH_CONNECTION=${SSH_CONNECTION}
    depends_on:
      - oscb_mysql
    volumes:
      - user_storage:/usr/src/app/storage/
    networks:
      - oscb-network

  oscb_react:
    container_name: oscb_react_container
    image: oscb_react
    build: ./ai-single-cell-ui/ai-single-cell-react
    ports:
      - "3000:3000"
    depends_on:
      - oscb_node
    environment:
      - HOST_URL=${HOST}
    networks:
      - oscb-network

  directus:
    container_name: oscb_directus_container
    image: directus/directus:9.24.0
    restart: unless-stopped
    ports:
        - 8055:8055
    volumes:
        - ./uploads:/directus/uploads
    depends_on:
        - oscb_mysql
    env_file:
        - ./ai-single-cell-ui/.env
    networks:
      - oscb-network

  oscb_flask:
    build:
      context: ./ai-single-cell-ui/ai-single-cell-flask
      dockerfile: Dockerfile
    container_name: oscb_flask_container
    image: oscb_flask
    restart: always
    ports:
      - "5003:5003"
    networks:
      - oscb-network
    volumes:
      - user_storage:/usr/src/app/storage/

networks:
  oscb-network:
    driver: bridge

volumes:
  Predictions: 
  Uploads:
  Errors:
  user_storage: {}

