version: "3"

services:
      
  api:
    build: 
      context: ./
    command: gunicorn main:app --bind 0.0.0.0:5000  -k uvicorn.workers.UvicornWorker
    expose:
      - 5000
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-http.rule=Host(`digbio-devel.missouri.edu`)
      - traefik.http.routers.app-http.tls=true
      - traefik.http.routers.app-http.tls.certresolver=letsencrypt

  traefik:
    image: traefik:v2.3
    ports:
      - 5000:5000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/services/traefik/traefik.toml:/etc/traefik/traefik.toml
      - traefik-public-certificates:/certificates


volumes:
  cache:
    driver: local
  traefik-public-certificates:
