# 
FROM python:3.9

# 
WORKDIR /code

# 
COPY ./requirements_new.txt /code/requirements_new.txt

# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements_new.txt

# Set environment variables
ENV place=docker

# 
COPY . /code/

EXPOSE 5000
# 
CMD ["gunicorn", "main:app", "--bind", "0.0.0.0:5000",\
    "--worker-class", "uvicorn.workers.UvicornWorker"]
