apiVersion: v1
kind: Secret
metadata:
  name: oscb-secret
  namespace: oscb
type: Opaque
stringData:
  # RabbitMQ
  RABBITMQ_DEFAULT_PASS: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
  
  # Node & MySQL
  DBPASSWORD: "Shirley@2410"
  MYSQL_ROOT_PASSWORD: "Shirley@2410"
  
  # Directus
  KEY: "secret"
  SECRET: "secret"
  ADMIN_PASSWORD: "d1r3ctu5"
  
  # Mongo Express
  ME_CONFIG_BASICAUTH_USERNAME: "admin"
  ME_CONFIG_BASICAUTH_PASSWORD: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
  
  # Node Env
  JWT_TOKEN_SECRET: "a84b03c2ca3e6860485eaf86e236ae7fe4d9170cd2c03f69f22f79ca34500737"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "465"
  EMAIL_ACCOUNT: "muloc.group@gmail.com"
  EMAIL_PWD: "hetyrefrqntjfcbv"
