apiVersion: apps/v1
kind: Deployment
metadata:
  name: oscb-redis
  namespace: oscb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oscb-redis
  template:
    metadata:
      labels:
        app: oscb-redis
    spec:
      containers:
        - name: redis
          image: redis:6-alpine
          command: ["redis-server", "--port", "6388", "--save", "20", "1", "--loglevel", "warning", "--requirepass", "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"]
          ports:
            - containerPort: 6388
---
apiVersion: v1
kind: Service
metadata:
  name: oscb-redis
  namespace: oscb
spec:
  selector:
    app: oscb-redis
  ports:
    - protocol: TCP
      port: 6388
      targetPort: 6388
